name: boilr
description: A Dart CLI tool for generating Flutter projects with pre-configured packages and architecture.
version: 0.0.1
repository: https://github.com/shadatrahman/boilr

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  path: ^1.9.0
  io: ^1.0.4

dev_dependencies:
  lints: ^6.0.0
